# Generated by Django 3.0.8 on 2022-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sortno',
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='productcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
