# Generated by Django 3.0.8 on 2022-06-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_accessories_battery_batterycapacity_batteryconnectortype_batterymake_batterytype_certcard_chargerrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=120, unique=True)),
                ('productcode', models.PositiveIntegerField(unique=True)),
                ('vehicleinvoiceno', models.CharField(max_length=120)),
                ('vehicleinvoicedatefromhe', models.DateField()),
                ('exciseinvoiceno', models.CharField(max_length=120)),
                ('vehiclechassisno', models.CharField(max_length=120)),
                ('motorno', models.CharField(max_length=120)),
                ('controllerno', models.CharField(max_length=120)),
                ('chargerno', models.CharField(max_length=120)),
                ('ownersmanualno', models.CharField(max_length=120)),
                ('heronumberplate', models.CharField(blank=True, default='NA', max_length=20, null=True)),
                ('engravednumberonbattery', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('batterycompleteserialno', models.CharField(blank=True, max_length=50, null=True)),
                ('available', models.CharField(default='Yes', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Battery')),
                ('batterycapacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BatteryCapacity')),
                ('batteryconnectortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BatteryConnectorType')),
                ('batterymake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BatteryMake')),
                ('certcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CertCard')),
                ('chargerrating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ChargerRating')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.VehicleModel')),
                ('pdistatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.PdiStatus')),
                ('rvmlhrh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.RvmLhrh')),
                ('toolkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ToolkitStatus')),
                ('typeofbattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BatteryType')),
            ],
        ),
    ]
