# Generated by Django 3.0.8 on 2022-06-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vehiclestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.VehicleStock')),
                ('productdesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
