# Generated by Django 3.0.8 on 2022-06-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_vehiclestockdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestock',
            name='productdesc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
