# Generated by Django 3.0.8 on 2022-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_vehiclestock_productdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestock',
            name='productcode',
            field=models.PositiveIntegerField(),
        ),
    ]
