# Generated by Django 3.0.8 on 2022-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220623_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestock',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
