# Generated by Django 3.0.8 on 2022-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220623_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestock',
            name='batterycompleteserialno2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='motorno',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='vehiclechassisno',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
