# Generated by Django 3.0.8 on 2022-06-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220625_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartsStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=120, unique=True)),
                ('materialcode', models.PositiveIntegerField()),
                ('materialdesc', models.CharField(max_length=120)),
                ('vendorinvoicedate', models.DateField()),
                ('vendorinvoiceno', models.CharField(max_length=120)),
                ('available', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Uom')),
            ],
        ),
    ]
