# Generated by Django 3.0.8 on 2022-07-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_sparepartsstock_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('mobileno', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField()),
                ('pay_reason', models.CharField(max_length=120)),
                ('pay_no', models.CharField(max_length=120)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('pay_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.PaymentMode')),
            ],
        ),
    ]
