# Generated by Django 3.0.8 on 2022-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_moneyreceipt_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyreceipt',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
