# Generated by Django 3.0.8 on 2022-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220708_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestock',
            name='chargerno2',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
