from django.urls import path

from .views import (
    create_supplier,
    create_buyer,
    create_season,
    create_drop,
    create_product,
    create_order,
    create_delivery,
    create_accessories,
    create_vehicle_stock,
    create_battery,
    create_vehicle_model,
    create_color,
    create_charger_rating,
    create_toolkit_status,
    create_rvm_lhrh,
    create_cert_card,
    create_pdi_status,
    create_battery_make,
    create_battery_connector_type,
    create_battery_type,
    create_battery_capacity,

    SupplierListView,
    BuyerListView,
    SeasonListView,
    DropListView,
    ProductListView,
    OrderListView,
    DeliveryListView,
    AccessoriesListView,
    VehicleListView,
    BatteriesListView,
    VehicleModelListView,
    ColorListView,
    ChargerRatingListView,
    ToolkitStatusListView,
    RvmLhrhListView,
    CertCardListView,
    PdiStatusListView,
    BatteryMakeListView,
    BatteryConnectorTypeListView,
    BatteryTypeListView,
    BatteryCapacityListView,
    SearchResultsView,
)

urlpatterns = [
    path('create-supplier/', create_supplier, name='create-supplier'),
    path('create-buyer/', create_buyer, name='create-buyer'),
    path('create-season/', create_season, name='create-season'),
    path('create-drop/', create_drop, name='create-drop'),
    path('create-product/', create_product, name='create-product'),
    path('create-order/', create_order, name='create-order'),
    path('create-delivery/', create_delivery, name='create-delivery'),
    path('create-accessories/', create_accessories, name='create-accessories'),
    path('create-vehicle-stock/', create_vehicle_stock, name='create-vehicle-stock'),
    path('create-battery/', create_battery, name='create-battery'),
    path('create-vehicle-model/', create_vehicle_model, name='create-vehicle-model'),
    path('create-color/', create_color, name='create-color'),
    path('create-charger-rating/', create_charger_rating, name='create-charger-rating'),
    path('create-toolkit-status/', create_toolkit_status, name='create-toolkit-status'),
    path('create-rvm-lhrh/', create_rvm_lhrh, name='create-rvm-lhrh'),
    path('create-cert-card/', create_cert_card, name='create-cert-card'),
    path('create-pdi-status/', create_pdi_status, name='create-pdi-status'),
    path('create-battery-make/', create_battery_make, name='create-battery-make'),
    path('create-battery-connector-type/', create_battery_connector_type, name='create-battery-connector-type'),
    path('create-battery-type/', create_battery_type, name='create-battery-type'),
    path('create-battery-capacity/', create_battery_capacity, name='create-battery-capacity'),

    path('battery-list/', BatteriesListView.as_view(), name='battery-list'),
    path('vehicle-model-list/', VehicleModelListView.as_view(), name='vehicle-model-list'),
    path('color-list/', ColorListView.as_view(), name='color-list'),
    path('charger-rating-list/', ChargerRatingListView.as_view(), name='charger-rating-list'),
    path('toolkit-status-list/', ToolkitStatusListView.as_view(), name='toolkit-status-list'),
    path('rvm-lhrh-list/', RvmLhrhListView.as_view(), name='rvm-lhrh-list'),
    path('cert-card-list/', CertCardListView.as_view(), name='cert-card-list'),
    path('pdi-status-list/', PdiStatusListView.as_view(), name='pdi-status-list'),
    path('battery-make-list/', BatteryMakeListView.as_view(), name='battery-make-list'),
    path('battery-connector-type-list/', BatteryConnectorTypeListView.as_view(), name='battery-connector-type-list'),
    path('battery-type-list/', BatteryTypeListView.as_view(), name='battery-type-list'),
    path('battery-capacity-list/', BatteryCapacityListView.as_view(), name='battery-capacity-list'),
    path('supplier-list/', SupplierListView.as_view(), name='supplier-list'),
    path('buyer-list/', BuyerListView.as_view(), name='buyer-list'),
    path('season-list/', SeasonListView.as_view(), name='season-list'),
    path('drop-list/', DropListView.as_view(), name='drop-list'),
    path('product-list/', ProductListView.as_view(), name='product-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('delivery-list/', DeliveryListView.as_view(), name='delivery-list'),
    path('accessories-list/', AccessoriesListView.as_view(), name='accessories-list'),
    path('vehicle-list/', VehicleListView.as_view(), name='vehicle-list'),
    path("search/", SearchResultsView.as_view(), name="search"),
]